# Generated by Django 5.0.2 on 2024-02-17 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_userfeed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeed",
            name="posts",
            field=models.ManyToManyField(related_name="user_feed", to="blog.post"),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("subscriber", "blog"), name="subscriber_blog_constraint"
            ),
        ),
    ]
